# User config
author: "An Bui"
tagline: "prints and other things"
description: "Email me if you want to buy anything!"
keywords: "prints and other things"
email: "a.thanh.bui@gmail.com"
twitter: "https://twitter.com/_anbui"
github: "https://github.com/an-bui"
instagram: "https://instagram.com/corvilady"

# Site config
remote_theme: arnolds/pineapple
baseurl: "/shop"
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
categories: projects, stickers, cards